[package]
name = "debpkg"
version = "0.1.0"
authors = ["Matt Schulte <schultetwin1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ar = "0.8"
flate2 = "1.0"
regex = "1.3"
tar = "0.4"
tempfile = "3.1"
xz2 = "0.1"

[dev-dependencies]
assert_matches = "1.2"