[package]
name = "debpkg"
version = "0.1.0"
authors = ["Matt Schulte <schultetwin1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ar = "0.8.0"
flate2 = "1.0.12"
rust-lzma = "0.4.0"
tar = "0.4.26"
tempfile = "3.1.0"
